# Generated by Django 4.1.1 on 2022-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wallet",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
