# Generated by Django 4.1.1 on 2022-09-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
