# Generated by Django 4.1.1 on 2022-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_remove_cart_total_itens_remove_cart_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_itens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cart",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
