# Generated by Django 4.1.1 on 2022-09-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_cart_total_itens_cart_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="total_itens",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
    ]
