# Generated by Django 4.1.1 on 2022-09-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0005_remove_cart_products_cart_product_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_finalized",
            field=models.BooleanField(default=False),
        ),
    ]
